"""Shared constants for the core foundation module."""

from __future__ import annotations

from pathlib import Path

DEFAULT_APP_NAME = "AI-Librarian"
DEFAULT_APP_VERSION = "0.1.0"
DEFAULT_ENVIRONMENT = "development"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
DEFAULT_LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
DEFAULT_SUPPORTED_EXTENSIONS = (".pdf", ".docx", ".md", ".txt")
DEFAULT_AUTO_CREATE_FOLDERS = True
DEFAULT_MAX_FILE_SIZE_MB = 50
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30
DEFAULT_DATA_DIRNAME = "data"
DEFAULT_DOCS_DIRNAME = "docs"
DEFAULT_OUTPUT_DIRNAME = "output"
DEFAULT_PROMPTS_DIRNAME = "prompts"
DEFAULT_TEMPLATES_DIRNAME = "templates"
DEFAULT_LOGS_DIRNAME = "logs"

LOGGER_NAME = "ai_librarian"

ENV_APP_NAME = "APP_NAME"
ENV_APP_VERSION = "APP_VERSION"
ENV_ENVIRONMENT = "APP_ENVIRONMENT"
ENV_DEBUG = "APP_DEBUG"
ENV_LOG_LEVEL = "APP_LOG_LEVEL"
ENV_LOG_FILE = "APP_LOG_FILE"
ENV_DATA_DIR = "APP_DATA_DIR"
ENV_DOCS_DIR = "APP_DOCS_DIR"
ENV_OUTPUT_DIR = "APP_OUTPUT_DIR"
ENV_PROMPTS_DIR = "APP_PROMPTS_DIR"
ENV_TEMPLATES_DIR = "APP_TEMPLATES_DIR"
ENV_SUPPORTED_EXTENSIONS = "APP_SUPPORTED_EXTENSIONS"
ENV_AUTO_CREATE_FOLDERS = "APP_AUTO_CREATE_FOLDERS"
ENV_MAX_FILE_SIZE_MB = "APP_MAX_FILE_SIZE_MB"
ENV_REQUEST_TIMEOUT_SECONDS = "APP_REQUEST_TIMEOUT_SECONDS"
ENV_PROJECT_ROOT = "PROJECT_ROOT"

DEFAULT_PROJECT_ROOT = Path(__file__).resolve().parents[2]
